### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules + Custom build CK Editor

### ISSUE THREAD

**Issue by DezanProgramador** [rickx81/ckeditor5-line-height#1]
My application is in Angular, and I'm using a custom build generated here https://ckeditor.com/ckeditor-5/online-builder/, but after adding this plugin, I get this runtime error: Uncaught (in promise): CKEditorError: ckeditor-duplicated-modules.

Any tips?

**Comment by rickx81** [comment]
It may be a version issue, I will upgrade the version later.
[CKeditor5 Requirements](https://ckeditor.com/docs/ckeditor5/latest/installation/plugins/installing-plugins.html#requirements)

**Comment by DezanProgramador** [comment]
I used the version you updated, but I still have the same error. In my build, I use version 40.0.0 of CKEditor and its native plugins. Any idea what I can do?

**Comment by rickx81** [comment]
> I used the version you updated, but I still have the same error. In my build, I use version 40.0.0 of CKEditor and its native plugins. Any idea what I can do?

Try installing version @rickx/ckeditor5-line-height@40.0.0 or upgrading your packages and plugins to the same version.

**Comment by DezanProgramador** [comment]
Thank you in advance for your attention. I tried this version  @rickx/ckeditor5-line-height@40.0.0, but I encountered the same error: ERROR Error: Uncaught (in promise): CKEditorError: ckeditor-duplicated-modules

**Comment by rickx81** [comment]
I tried to use the official plugin in a CKEditor built with the Online Builder but that failed too. May build from the online builder does not support installation of other plugins.
My application uses CKEditor built from source code and it works fine. Can you try [Using a custom CKEditor 5 build](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/angular.html#using-a-custom-ckeditor-5-build) and [Building the editor from source](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source)?
Sorry I don't know how to use angular and this is a vue example [StackBlitz](https://stackblitz.com/edit/vitejs-vite-mrtjfp?file=src%2Fcomponents%2FCKEditor.vue)

**Comment by zhangqhzz** [comment]
react :
const element = document.getElementById('myElementId')!
ClassicEditor
  .create(element, {
    plugins: [
      /* ..., */
      LineHeight //   prompt 不能将类型“typeof LineHeight”分配给类型“string | PluginConstructor<Editor>”
    ],
    
  })
  .then(/* ... */)
  .catch(/* ... */)

**Comment by rickx81** [comment]
> react : const element = document.getElementById('myElementId')! ClassicEditor .create(element, { plugins: [ /* ..., */ LineHeight // prompt 不能将类型“typeof LineHeight”分配给类型“string | PluginConstructor” ],
> 
> }) .then(/* ... _/) .catch(/_ ... */)

If your CKEditor >= 42.0.0, try update @rickx/ckeditor5-line-height@42.0.0

**Comment by zhangqhzz** [comment]
Thanks.
I saw the latest version today, and the issue has been resolved after the update.


求真
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rickx81/ckeditor5-line-height"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月12日(星期五) 晚上10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rickx81/ckeditor5-line-height] CKEditorError: ckeditor-duplicated-modules + Custom build CK Editor (Issue #1)





  
react : const element = document.getElementById('myElementId')! ClassicEditor .create(element, { plugins: [ /* ..., */ LineHeight // prompt 不能将类型“typeof LineHeight”分配给类型“string | PluginConstructor” ],
 
}) .then(/* ... /) .catch(/ ... */)
  
What version is CKEditor?

**Comment by rogozind** [comment]
I am still seeing it. On ckeditor 42.0.2.

This is my relevant packages:

    "@ckeditor/ckeditor5-alignment": "^42.0.2",
    "@ckeditor/ckeditor5-autoformat": "^42.0.2",
    "@ckeditor/ckeditor5-autosave": "^42.0.2",
    "@ckeditor/ckeditor5-basic-styles": "^42.0.2",
    "@ckeditor/ckeditor5-block-quote": "^42.0.2",
    "@ckeditor/ckeditor5-build-inline": "^42.0.2",
    "@ckeditor/ckeditor5-clipboard": "^42.0.2",
    "@ckeditor/ckeditor5-cloud-services": "^42.0.2",
    "@ckeditor/ckeditor5-comments": "^42.0.2",
    "@ckeditor/ckeditor5-core": "^42.0.2",
    "@ckeditor/ckeditor5-dev-translations": "^41.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^41.0.0",
    "@ckeditor/ckeditor5-easy-image": "^42.0.2",
    "@ckeditor/ckeditor5-editor-classic": "^42.0.2",
    "@ckeditor/ckeditor5-editor-inline": "^42.0.2",
    "@ckeditor/ckeditor5-engine": "^42.0.2",
    "@ckeditor/ckeditor5-enter": "^42.0.2",
    "@ckeditor/ckeditor5-essentials": "^42.0.2",
    "@ckeditor/ckeditor5-font": "^42.0.2",
    "@ckeditor/ckeditor5-heading": "^42.0.2",
    "@ckeditor/ckeditor5-html-support": "^42.0.2",
    "@ckeditor/ckeditor5-image": "^42.0.2",
    "@ckeditor/ckeditor5-indent": "^42.0.2",
    "@ckeditor/ckeditor5-inspector": "^4.1.0",
    "@ckeditor/ckeditor5-link": "^42.0.2",
    "@ckeditor/ckeditor5-list": "^42.0.2",
    "@ckeditor/ckeditor5-mention": "^42.0.2",
    "@ckeditor/ckeditor5-paragraph": "^42.0.2",
    "@ckeditor/ckeditor5-paste-from-office": "^42.0.2",
    "@ckeditor/ckeditor5-real-time-collaboration": "^42.0.2",
    "@ckeditor/ckeditor5-remove-format": "^42.0.2",
    "@ckeditor/ckeditor5-source-editing": "^42.0.2",
    "@ckeditor/ckeditor5-special-characters": "^42.0.2",
    "@ckeditor/ckeditor5-table": "^42.0.2",
    "@ckeditor/ckeditor5-theme-lark": "^42.0.2",
    "@ckeditor/ckeditor5-track-changes": "^42.0.2",
    "@ckeditor/ckeditor5-upload": "^42.0.2",
    "@ckeditor/ckeditor5-utils": "^42.0.2",
    "@ckeditor/ckeditor5-watchdog": "^42.0.2",
    "@ckeditor/vite-plugin-ckeditor5": "^0.1.3",

**Comment by rickx81** [comment]
> I am still seeing it. On ckeditor 42.0.2.
> 
> This is my relevant packages:
> 
> ```
> "@ckeditor/ckeditor5-alignment": "^42.0.2",
> "@ckeditor/ckeditor5-autoformat": "^42.0.2",
> "@ckeditor/ckeditor5-autosave": "^42.0.2",
> "@ckeditor/ckeditor5-basic-styles": "^42.0.2",
> "@ckeditor/ckeditor5-block-quote": "^42.0.2",
> "@ckeditor/ckeditor5-build-inline": "^42.0.2",
> "@ckeditor/ckeditor5-clipboard": "^42.0.2",
> "@ckeditor/ckeditor5-cloud-services": "^42.0.2",
> "@ckeditor/ckeditor5-comments": "^42.0.2",
> "@ckeditor/ckeditor5-core": "^42.0.2",
> "@ckeditor/ckeditor5-dev-translations": "^41.0.0",
> "@ckeditor/ckeditor5-dev-utils": "^41.0.0",
> "@ckeditor/ckeditor5-easy-image": "^42.0.2",
> "@ckeditor/ckeditor5-editor-classic": "^42.0.2",
> "@ckeditor/ckeditor5-editor-inline": "^42.0.2",
> "@ckeditor/ckeditor5-engine": "^42.0.2",
> "@ckeditor/ckeditor5-enter": "^42.0.2",
> "@ckeditor/ckeditor5-essentials": "^42.0.2",
> "@ckeditor/ckeditor5-font": "^42.0.2",
> "@ckeditor/ckeditor5-heading": "^42.0.2",
> "@ckeditor/ckeditor5-html-support": "^42.0.2",
> "@ckeditor/ckeditor5-image": "^42.0.2",
> "@ckeditor/ckeditor5-indent": "^42.0.2",
> "@ckeditor/ckeditor5-inspector": "^4.1.0",
> "@ckeditor/ckeditor5-link": "^42.0.2",
> "@ckeditor/ckeditor5-list": "^42.0.2",
> "@ckeditor/ckeditor5-mention": "^42.0.2",
> "@ckeditor/ckeditor5-paragraph": "^42.0.2",
> "@ckeditor/ckeditor5-paste-from-office": "^42.0.2",
> "@ckeditor/ckeditor5-real-time-collaboration": "^42.0.2",
> "@ckeditor/ckeditor5-remove-format": "^42.0.2",
> "@ckeditor/ckeditor5-source-editing": "^42.0.2",
> "@ckeditor/ckeditor5-special-characters": "^42.0.2",
> "@ckeditor/ckeditor5-table": "^42.0.2",
> "@ckeditor/ckeditor5-theme-lark": "^42.0.2",
> "@ckeditor/ckeditor5-track-changes": "^42.0.2",
> "@ckeditor/ckeditor5-upload": "^42.0.2",
> "@ckeditor/ckeditor5-utils": "^42.0.2",
> "@ckeditor/ckeditor5-watchdog": "^42.0.2",
> "@ckeditor/vite-plugin-ckeditor5": "^0.1.3",
> ```

try this
[Update to CKEditor 5 v42.x](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-42.html)
[Migrating from customized builds](https://ckeditor.com/docs/ckeditor5/latest/updating/nim-migration/customized-builds.html)

**Comment by rogozind** [comment]
That helped, we had to switch to this new method.

**Comment by zhangqhzz** [comment]
Thanks.
&nbsp;


求真
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tony ***@***.***&gt;; 
发送时间: 2024年7月25日(星期四) 晚上10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rickx81/ckeditor5-line-height] CKEditorError: ckeditor-duplicated-modules + Custom build CK Editor (Issue #1)














  
I am still seeing it. On ckeditor 42.0.2.
 
This is my relevant packages:
 ***@***.***/ckeditor5-alignment": "^42.0.2", ***@***.***/ckeditor5-autoformat": "^42.0.2", ***@***.***/ckeditor5-autosave": "^42.0.2", ***@***.***/ckeditor5-basic-styles": "^42.0.2", ***@***.***/ckeditor5-block-quote": "^42.0.2", ***@***.***/ckeditor5-build-inline": "^42.0.2", ***@***.***/ckeditor5-clipboard": "^42.0.2", ***@***.***/ckeditor5-cloud-services": "^42.0.2", ***@***.***/ckeditor5-comments": "^42.0.2", ***@***.***/ckeditor5-core": "^42.0.2", ***@***.***/ckeditor5-dev-translations": "^41.0.0", ***@***.***/ckeditor5-dev-utils": "^41.0.0", ***@***.***/ckeditor5-easy-image": "^42.0.2", ***@***.***/ckeditor5-editor-classic": "^42.0.2", ***@***.***/ckeditor5-editor-inline": "^42.0.2", ***@***.***/ckeditor5-engine": "^42.0.2", ***@***.***/ckeditor5-enter": "^42.0.2", ***@***.***/ckeditor5-essentials": "^42.0.2", ***@***.***/ckeditor5-font": "^42.0.2", ***@***.***/ckeditor5-heading": "^42.0.2", ***@***.***/ckeditor5-html-support": "^42.0.2", ***@***.***/ckeditor5-image": "^42.0.2", ***@***.***/ckeditor5-indent": "^42.0.2", ***@***.***/ckeditor5-inspector": "^4.1.0", ***@***.***/ckeditor5-link": "^42.0.2", ***@***.***/ckeditor5-list": "^42.0.2", ***@***.***/ckeditor5-mention": "^42.0.2", ***@***.***/ckeditor5-paragraph": "^42.0.2", ***@***.***/ckeditor5-paste-from-office": "^42.0.2", ***@***.***/ckeditor5-real-time-collaboration": "^42.0.2", ***@***.***/ckeditor5-remove-format": "^42.0.2", ***@***.***/ckeditor5-source-editing": "^42.0.2", ***@***.***/ckeditor5-special-characters": "^42.0.2", ***@***.***/ckeditor5-table": "^42.0.2", ***@***.***/ckeditor5-theme-lark": "^42.0.2", ***@***.***/ckeditor5-track-changes": "^42.0.2", ***@***.***/ckeditor5-upload": "^42.0.2", ***@***.***/ckeditor5-utils": "^42.0.2", ***@***.***/ckeditor5-watchdog": "^42.0.2", ***@***.***/vite-plugin-ckeditor5": "^0.1.3",   
try this
 Update to CKEditor 5 v42.x
 Migrating from customized builds
